[project]
name = "summer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "camel-tools",
  "qdrant_client",
  "telebot",
  "telegramify-markdown",
  "pydantic",
  "pydantic-ai",
  "pydantic-harness",
  "fastapi",
  "logfire[httpx]",
  "fastembed",
  "sentence_transformers",
  "uvicorn",
  "psycopg2-binary",
  "PyYAML>=6.0,<7",
]
